### ISSUE TITLE
Running st pipeline unrecognized arguments

### ISSUE THREAD

**Issue by ajyaca** [SpatialTranscriptomicsResearch/st_pipeline#125]
Hello

Thank you very much for your work.
I'm trying to run the pipeline using the following code :
st_pipeline_run.py
--output-folder $OUTPUT
--ids $ID
--ref-map $MAP
--ref-annotation $ANN
--expName $EXP
--htseq-no-ambiguous
--verbose
--log-file $OUTPUT/${EXP}_log.txt
--allowed-kmer 5
--mapping-threads 20
--temp-folder $TMP
--no-clean-up
--umi-start-position 16
--umi-end-position 26
--overhang 0
--min-length-qual-trimming 10
$FW $RV

I get this error message : st_pipeline_run.py: error: unrecognized arguments: --allowed-kmer 5 --mapping-threads 20 --overhang 0

Do you know how I could fix the problem ?

Thank you very much for your help!!

A

**Comment by jfnavarro** [comment]
Hi and thanks for your message! 

I believe you need to update some of the parameters since the names were updated recently to be more comprehensive. You can use `st_pipeline_run.py --help` to see the full list of parameters. Also, note that this repository will be deprecated so I would advice to use the original one 

https://github.com/jfnavarro/st_pipeline

Best,
Jose

**Comment by ajyaca** [comment]
Hi Jose
Thank you so much.I changed the argument and it worked.Sorry for bothering you again but when I try to run the pipeline , I got this error message.
ST Pipeline, logger created

Error running the pipeline

Error parsing parameters.

Invalid input files /gpfs/loomis/pi/kaminski/public/Backup/Aurelien/FastQc/Sample_319-42/2.rawdata/319-42_S27_L004_R2_001.fastq.gz /gpfs/loomis/pi/kaminski/public/Backup/Aurelien/FastQc/Sample_319-42/R1/319-42_S27_L004_R1_001.fastqc.gz

This is what I can find in the log.txt file:ERROR:STPipeline:Error while starting the decompression of GZIP/BZIP2 input files /gpfs/loomis/pi/kaminski/public/Backup/Aurelien/FastQc/Sample_319-42/319-42_S27_L004_R2_001_processed.fastq.gz /gpfs/loomis/pi/kaminski/public/Backup/Aurelien/FastQc/Sample_319-42/R1/319-42_S27_L004_R1_001.fastq.gz
I tried to decompress the files, it worked well.Any clue to solve the problem ?
Thanks again for your help
Aurelien


    Le lundi 30 août 2021, 04:19:10 UTC−4, José Fernández Navarro ***@***.***> a écrit :  
 
 


Hi and thanks for your message!

I believe you need to update some of the parameters since the names were updated recently to be more comprehensive. You can use st_pipeline_run.py --help to see the full list of parameters. Also, note that this repository will be deprecated so I would advice to use the original one

https://github.com/jfnavarro/st_pipeline

Best,
Jose

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jfnavarro** [comment]
Hi Aurelien, 

Mmmm, this sounds weird. How did you compress/decompress the files? Are those paths correct and reachable by your user?

**Comment by ajyaca** [comment]
Hi Jose 
Thanks for taking the time for answering.I used gzip. I'm working on a cluster and the path are reachable, I checked.Here are the format of the files 319-42_S27_L008_R1_001.fastq.gz.My samples have been sequenced on 3 differents lanes, should I merged first the Fastq files and then run the pipeline ?Sorry again for bothering you 
Aurelien    Le mardi 31 août 2021, 03:26:55 UTC−4, José Fernández Navarro ***@***.***> a écrit :  
 
 


Hi Aurelien,

Mmmm, this sounds weird. How did you compress/decompress the files? Are those paths correct and reachable by your user?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jfnavarro** [comment]
You should merge the 3 different lanes indeed but also make sure that the files are correct FASTQ files, perhaps run FASTQC on them.

**Comment by jocelynnijin** [comment]
> Hi Jose
> Thank you so much.I changed the argument and it worked.Sorry for bothering you again but when I try to run the pipeline , I got this error message.
> ST Pipeline, logger created
> 
> Error running the pipeline
> 
> Error parsing parameters.
> 
> Invalid input files /gpfs/loomis/pi/kaminski/public/Backup/Aurelien/FastQc/Sample_319-42/2.rawdata/319-42_S27_L004_R2_001.fastq.gz /gpfs/loomis/pi/kaminski/public/Backup/Aurelien/FastQc/Sample_319-42/R1/319-42_S27_L004_R1_001.fastqc.gz
> 
> This is what I can find in the log.txt file:ERROR:STPipeline:Error while starting the decompression of GZIP/BZIP2 input files /gpfs/loomis/pi/kaminski/public/Backup/Aurelien/FastQc/Sample_319-42/319-42_S27_L004_R2_001_processed.fastq.gz /gpfs/loomis/pi/kaminski/public/Backup/Aurelien/FastQc/Sample_319-42/R1/319-42_S27_L004_R1_001.fastq.gz
> I tried to decompress the files, it worked well.Any clue to solve the problem ?
> Thanks again for your help
> Aurelien
> 
> 
>     Le lundi 30 août 2021, 04:19:10 UTC−4, José Fernández Navarro ***@***.***> a écrit :
> 
> 
> 
> 
> Hi and thanks for your message!
> 
> I believe you need to update some of the parameters since the names were updated recently to be more comprehensive. You can use st_pipeline_run.py --help to see the full list of parameters. Also, note that this repository will be deprecated so I would advice to use the original one
> 
> https://github.com/jfnavarro/st_pipeline
> 
> Best,
> Jose
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

Hi Aurelien,

I am trying to run the same code you ran but no success yet. Thanks for the question that reminds me to change the name of parameters. However, I am still experiencing this error message, did this happen to you? 
"
ST Pipeline, sanity check passed. Starting the run...
Error running the pipeline
Processing records: 0record [00:00, ?record/s]
Traceback (most recent call last):
  File "/home/nij2/miniconda3/envs/stpipeline/bin/taggd_demultiplex", line 8, in <module>
    sys.exit(main())
  File "/home/nij2/miniconda3/envs/stpipeline/lib/python3.10/site-packages/scripts/taggd_demultiplex.py", line 447, in main
    print(str(demux.stats))
  File "/home/nij2/miniconda3/envs/stpipeline/lib/python3.10/site-packages/taggd/core/statistics.py", line 40, in __str__
    f"# Matches: {mat}   [{mat * 100.0 / self.total_reads:.2f}%]\n"
ZeroDivisionError: float division by zero"

Thank you!
Jocelyn
